name: DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script
        run: |
          echo "Starting pipeline"
          date
          ls -la
          echo "Pipeline completed"

      - name: Create artifact
        run: echo "This is my build file" > output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: output.txt
